GET http://localhost:3000/



###


POST http://localhost:3000/usuarios/add
Content-Type: application/json

{
    "username": "Catalejo",
    "password": "123pee",
    "fullname": "Pedro Provenzano",
    "email": "pedroprov0@gmail.com",
    "phone": 51532434,
    "sendDir": "Blabla 2000"
}

###

GET http://localhost:3000/usuarios/login
Content-Type: application/json

{
    "username": "Mrklus",
    "password": "123pee"
}

###

GET http://localhost:3000/usuarios/
Content-Type: application/json

{
    "username": "Mrklus",
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1ya2x1cyIsImlhdCI6MTYxMzA5MTMxNSwiZXhwIjoxNjEzMDk0OTE1fQ.wZqKPNiSVSG8T-isbrGY99nrouTxDfjofetPxt0kkjc",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1ya2x1cyIsImlhdCI6MTYxMzA5MTMxNX0.Dk-gn0CoCDBmW3LIpLA6XfPciItBRSbUOzR4sdD375c"
}


###

GET http://localhost:3000/usuarios/edit
Content-Type: application/json

{
    "username": "Mrklus",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFieXNzSG93bCIsImlhdCI6MTYxMzA3OTk3Nn0.x38MlI8B8RVatEW2j-BwJnmhG6N5vblrfM8dAqdqG8I",
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFieXNzSG93bCIsImlhdCI6MTYxMzA4MTA0NCwiZXhwIjoxNjEzMDgxMDU5fQ.WUrzN-w7Ite8anO1kT2Y6Xqsm9P1nxoIacQkFTJidsA"
}

###

GET http://localhost:3000/token
Content-Type: application/json

{
    "username": "Mrklus",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1ya2x1cyIsImlhdCI6MTYxMzA4NTI1OH0.ZjVAOlAYWhY5b9qSfl-j52LtpAZhy8_ElKHCx5ryQ9U"
}

###

POST http://localhost:3000/admin
Content-Type: application/json

{
    "username": "Mrklus",
    "password": "123pee",
    "fullname": "Pedro Provenzano",
    "email": "pedroprov0@gmail.com",
    "phone": "51532434",
    "sendDir": "Blabla 2000", 
    "adminpass": "123pee"
}


###

DELETE http://localhost:3000/usuarios/delete
Content-Type: application/json

{
    "username": "Mrklus",
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1ya2x1cyIsImlhdCI6MTYxMzA4NTI1OCwiZXhwIjoxNjEzMDg4ODU4fQ.0oVJQawbgcbxBmVzy7RBwBtAfugJ4opKl_Puus7VY-4",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1ya2x1cyIsImlhdCI6MTYxMzA4NTI1OH0.ZjVAOlAYWhY5b9qSfl-j52LtpAZhy8_ElKHCx5ryQ9U"
}

###

PUT http://localhost:3000/usuarios/edit
Content-Type: application/json

{
    "username": "Mrklus",
    "email": "treziktor@gmail.com",
    "celphone": "157547654",
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1ya2x1cyIsImlhdCI6MTYxMzA4OTc5NywiZXhwIjoxNjEzMDkzMzk3fQ.I9ZjL2_Fs8yCmdezzoOLDk9APVsG58M0vFy-7e-gl6c",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1ya2x1cyIsImlhdCI6MTYxMzA4NTI1OH0.ZjVAOlAYWhY5b9qSfl-j52LtpAZhy8_ElKHCx5ryQ9U"
}

###

GET http://localhost:3000/usuarios/logout
Content-Type: application/json

{
  "username": "Mrklus",
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1ya2x1cyIsImlhdCI6MTYxMzA5OTY2NywiZXhwIjoxNjEzMTAzMjY3fQ.V_L3gnNBS-RVoZvb55LCJ-3z3ZQwkx6Z8Whi8bw0Ia8",
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1ya2x1cyIsImlhdCI6MTYxMzA5OTY2N30.2wC1BACYzjLgZB4vl36PTJe9_1pf-p-nfybpQn6yMwg"
}