POST http://localhost:3000/menu/add
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1ya2x1cyIsImlhdCI6MTYxMzI1OTgxNywiZXhwIjoxNjEzMjc0MjE3fQ.mzRJI-3vb3mLwt5k-Z_TMSsQ8A2wJWHiK6uoc-8XX5Y
Content-Type: application/json

{
    "username": "Mrklus",
    "mealName": "Noquis",
    "price": 250
}

###

DELETE  http://localhost:3000/menu/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1ya2x1cyIsImlhdCI6MTYxMzE2NDkxNywiZXhwIjoxNjEzMTY4NTE3fQ.SrytZAHZqI9SJAW29m3SB7ZcqfDHXb6rfNTM8mbikX4
Content-Type: application/json

{
    "username": "Mrklus",
    "mealDelete": "Milanesa con papas"
}


###

GET  http://localhost:3000/menu/
Authorization: BearereyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1ya2x1cyIsImlhdCI6MTYxMzI1OTgxNywiZXhwIjoxNjEzMjc0MjE3fQ.mzRJI-3vb3mLwt5k-Z_TMSsQ8A2wJWHiK6uoc-8XX5Y
Content-Type: application/json

{
    "username": "Mrklus"
}


###

PUT  http://localhost:3000/menu/edit
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1ya2x1cyIsImlhdCI6MTYxMzE2NDkxNywiZXhwIjoxNjEzMTY4NTE3fQ.SrytZAHZqI9SJAW29m3SB7ZcqfDHXb6rfNTM8mbikX4
Content-Type: application/json

{
    "username": "Mrklus",
    "mealName": "Fideos con bolognesa",
    "price": 300
}