POST http://localhost:3000/pedidos/add
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1ya2x1cyIsImlhdCI6MTYxMzI2MTgwMCwiZXhwIjoxNjEzMjc2MjAwfQ.D40nZecC-wDfsTdTio8muxXgh89GLcsp0FbTWGtnq-g
Content-Type: application/json

{
    "username": "Mrklus",
    "platos": ["Fideos", "Milanesa", "Sanguche"],
    "payMethod": "Efectivo"
}


###

PUT http://localhost:3000/pedidos/edit
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1ya2x1cyIsImlhdCI6MTYxMzI2MTgwMCwiZXhwIjoxNjEzMjc2MjAwfQ.D40nZecC-wDfsTdTio8muxXgh89GLcsp0FbTWGtnq-g
Content-Type: application/json

{
    "username": "Mrklus",
    "orderID": 7,
    "orderState": "CONFIRMADO"
}

###

DELETE http://localhost:3000/pedidos/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1ya2x1cyIsImlhdCI6MTYxMzI2MTgwMCwiZXhwIjoxNjEzMjc2MjAwfQ.D40nZecC-wDfsTdTio8muxXgh89GLcsp0FbTWGtnq-g
Content-Type: application/json

{
    "username": "Mrklus",
    "DeleteID": 7
}


###

GET http://localhost:3000/pedidos/state/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1ya2x1cyIsImlhdCI6MTYxMzI2MTgwMCwiZXhwIjoxNjEzMjc2MjAwfQ.D40nZecC-wDfsTdTio8muxXgh89GLcsp0FbTWGtnq-g
Content-Type: application/json

{
    "username": "Mrklus",
    "orderID": 1
}

###

GET http://localhost:3000/pedidos/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1ya2x1cyIsImlhdCI6MTYxMzI2MTgwMCwiZXhwIjoxNjEzMjc2MjAwfQ.D40nZecC-wDfsTdTio8muxXgh89GLcsp0FbTWGtnq-g
Content-Type: application/json

{
    "username": "Mrklus",
    "usernameOrders": "Mrklus"
}


###

GET http://localhost:3000/pedidos/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1ya2x1cyIsImlhdCI6MTYxMzI2MTgwMCwiZXhwIjoxNjEzMjc2MjAwfQ.D40nZecC-wDfsTdTio8muxXgh89GLcsp0FbTWGtnq-g
Content-Type: application/json

{
    "username": "Mrklus"
}