POST http://localhost:3000/pedidos/add
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1ya2x1cyIsImlhdCI6MTYxMzI0NDY0MiwiZXhwIjoxNjEzMjU5MDQyfQ.EuLM8IxRv5AioHiZ0AClQnQebXuyeFAtypP4VpXJe24
Content-Type: application/json

{
    "username": "Mrklus",
    "platos": ["Fideos", "Milanesa", "Sanguche"],
    "payMethod": "Efectivo"
}


###

PUT http://localhost:3000/pedidos/edit
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1ya2x1cyIsImlhdCI6MTYxMzE3MzE1OCwiZXhwIjoxNjEzMTc2NzU4fQ.fzWfXn2UDBLxpkGyAbPMacMAmiBqlhVbvD_KvPAE8V8
Content-Type: application/json

{
    "username": "Mrklus",
    "orderID": 2,
    "orderState": "CONFIRMADO"
}

###

DELETE http://localhost:3000/pedidos/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1ya2x1cyIsImlhdCI6MTYxMzE3MzE1OCwiZXhwIjoxNjEzMTc2NzU4fQ.fzWfXn2UDBLxpkGyAbPMacMAmiBqlhVbvD_KvPAE8V8
Content-Type: application/json

{
    "username": "Mrklus",
    "DeleteID": 2
}


###

GET http://localhost:3000/pedidos/state/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1ya2x1cyIsImlhdCI6MTYxMzIzOTE4MywiZXhwIjoxNjEzMjUzNTgzfQ.k5WLw_rQYbTezPjBOqcauAJO05ffndPuD5Qhj7sYnoU
Content-Type: application/json

{
    "username": "Mrklus"
}


###

GET http://localhost:3000/pedidos/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1ya2x1cyIsImlhdCI6MTYxMzIzOTE4MywiZXhwIjoxNjEzMjUzNTgzfQ.k5WLw_rQYbTezPjBOqcauAJO05ffndPuD5Qhj7sYnoU
Content-Type: application/json

{
    "username": "Mrklus"
}