GET http://localhost:3000/



###


POST http://localhost:3000/usuarios/add
Content-Type: application/json


{
    "username": "Catalejo",
    "password": "123pee",
    "fullname": "Pedro Provenzano",
    "email": "pedroprov0@gmail.com",
    "phone": 51532434,
    "sendDir": "Blabla 2000"
}

###

GET http://localhost:3000/usuarios/login
Content-Type: application/json

{
    "username": "Mrklus",
    "password": "123pee"
}

###

GET http://localhost:3000/usuarios/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1ya2x1cyIsImlhdCI6MTYxMzE2MDEyMSwiZXhwIjoxNjEzMTYzNzIxfQ.5CIBqQ4Rgbl-SZWCBxJzSzTvmUvrJcB573QMWLnJF6E
Content-Type: application/json

{
    "username": "Mrklus",
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1ya2x1cyIsImlhdCI6MTYxMzA5MTMxNSwiZXhwIjoxNjEzMDk0OTE1fQ.wZqKPNiSVSG8T-isbrGY99nrouTxDfjofetPxt0kkjc",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1ya2x1cyIsImlhdCI6MTYxMzA5MTMxNX0.Dk-gn0CoCDBmW3LIpLA6XfPciItBRSbUOzR4sdD375c"
}


###

PUT http://localhost:3000/usuarios/edit
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1ya2x1cyIsImlhdCI6MTYxMzE2MDEyMSwiZXhwIjoxNjEzMTYzNzIxfQ.5CIBqQ4Rgbl-SZWCBxJzSzTvmUvrJcB573QMWLnJF6E
Content-Type: application/json

{
    "username": "Mrklus",
    "fullname": "Pedro Esteban Provenzano"    
}

###

GET http://localhost:3000/token
Content-Type: application/json

{
    "username": "Mrklus",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1ya2x1cyIsImlhdCI6MTYxMzE3MTE2Mn0.1Q91UpL9Il4baRTU-1xm_-Ph5ruMF5pLIreaHL1ArJc"
}

###

POST http://localhost:3000/admin
Content-Type: application/json

{
    "username": "Mrklus",
    "password": "123pee",
    "fullname": "Pedro Provenzano",
    "email": "pedroprov0@gmail.com",
    "phone": "51532434",
    "sendDir": "Blabla 2000", 
    "adminpass": "123pee"
}


###

DELETE http://localhost:3000/usuarios/delete
Content-Type: application/json

{
    "username": "Mrklus",
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1ya2x1cyIsImlhdCI6MTYxMzA4NTI1OCwiZXhwIjoxNjEzMDg4ODU4fQ.0oVJQawbgcbxBmVzy7RBwBtAfugJ4opKl_Puus7VY-4",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1ya2x1cyIsImlhdCI6MTYxMzA4NTI1OH0.ZjVAOlAYWhY5b9qSfl-j52LtpAZhy8_ElKHCx5ryQ9U"
}

###

PUT http://localhost:3000/usuarios/edit
Content-Type: application/json

{
    "username": "Mrklus",
    "email": "treziktor@gmail.com",
    "celphone": "157547654",
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1ya2x1cyIsImlhdCI6MTYxMzA4OTc5NywiZXhwIjoxNjEzMDkzMzk3fQ.I9ZjL2_Fs8yCmdezzoOLDk9APVsG58M0vFy-7e-gl6c",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1ya2x1cyIsImlhdCI6MTYxMzA4NTI1OH0.ZjVAOlAYWhY5b9qSfl-j52LtpAZhy8_ElKHCx5ryQ9U"
}

###

GET http://localhost:3000/usuarios/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1ya2x1cyIsImlhdCI6MTYxMzE2MjczMn0.sr1k1rupHQ4QiCQ5lVTtp5Vgq5sn7EiMNRAdK439dPI
Content-Type: application/json

{
  "username": "Mrklus"
}